unit TestUCalc;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UCalc, System.SysUtils;

type
  // Test methods for class TCalc

  TestTCalc = class(TTestCase)
  strict private
    FCalc: TCalc;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcularImposto;
  end;

implementation

procedure TestTCalc.SetUp;
begin
  FCalc := TCalc.Create;
end;

procedure TestTCalc.TearDown;
begin
  FCalc.Free;
  FCalc := nil;
end;

procedure TestTCalc.TestCalcularImposto;
var
  Tag: Integer;
begin
  // TODO: Setup method call parameters
  FCalc.UltimoNum := '3500';
  FCalc.CalcularImposto(0); // Imposto A = 0;
  Check(FCalc.ImpostoA = 200);
  FCalc.CalcularImposto(1); // Imposto B = 1;
  Check(FCalc.ImpostoB = 185);
  FCalc.CalcularImposto(2); // Imposto C = 2;
  Check(FCalc.Resultado = 385);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCalc.Suite);
end.

