unit TestUFuncionario;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, UFuncionario, UDataModule,Vcl.Dialogs;

type
  // Test methods for class TFuncionario

  TestTFuncionario = class(TTestCase)
  strict private
    FFuncionario: TFuncionario;
    FDataMod : TDataMod;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalculaINSS;
    procedure TestCalculaIR;
  end;

implementation

procedure TestTFuncionario.SetUp;
begin
  FDataMod := TDataMod.Create(Nil);
  FFuncionario := TFuncionario.Create;
  FFuncionario.ID := 1;
  FFuncionario.Nome := 'Teste INSS';
  FFuncionario.CPF := '228.825.668-08';
  FFuncionario.Salario := 1000;
end;

procedure TestTFuncionario.TearDown;
begin
  FFuncionario.Free;
  FFuncionario := nil;
end;

procedure TestTFuncionario.TestCalculaINSS;
var
  ReturnValue: Double;
begin
  ReturnValue := FFuncionario.CalculaINSS(1);
  Check(ReturnValue = 80);
  // TODO: Validate method results
end;

procedure TestTFuncionario.TestCalculaIR;
var
  ReturnValue: Double;
begin
  ReturnValue := FFuncionario.CalculaIR(1);
  Check(ReturnValue = 120);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFuncionario.Suite);
end.

